### ISSUE TITLE
FileExistError when running script on windows, runs fine on linux

### ISSUE THREAD

**Issue by lgspST** [IBM/ibm-cos-sdk-python-s3transfer#2]
My application uses the ibmcloudsql package installed from pip. Here I list the version of the various related packages:

* ibm-cos-sdk            2.4.4
* ibm-cos-sdk-core       2.4.4
* ibm-cos-sdk-s3transfer 2.4.4
* ibmcloudsql            0.2.23

The application calls run_sql from a SQLquery  instance.
While running run_sql the error occurs where it tries to rename a file in the local temp directory, generating the FileExistsError. 
I tried to remove the existing file from the debugger after the error occurred and it gives a permission error. 
Running the application from an administrator console doesn't solve the issue.
It looks to me that the temporary file to be removed is still opened when it tries to remove it.

Tested on 2 different pcs with windows 7 and windows 10. 
The linux version (packages installed with pip at the same version number) runs fine

```
---------------------------------------------------------------------------
FileExistsError                           Traceback (most recent call last)

~\Downloads\application\dataDL.py in query_ts(start, end, kind)
     36     print('loading data...')
     37     query = "SELECT * FROM " + k['cos_uri'] + "derived/ STORED AS PARQUET p1 WHERE p1.type='"+         kind +"' AND p1.source='periodic' AND p1.ts>"+str(ts_min)+" AND p1.ts<"+str(ts_max)+"  INTO " + k['cos_uri'] + k['cos_prefix'] + " STORED AS PARQUET PARTITIONED INTO 10 BUCKETS"
---> 38     res = sqlclient.run_sql(query)
     39     return res.sort_values('ts',ascending=True)
     40

c:\users\user_a\appdata\local\programs\python\python35\lib\site-packages\ibmcloudsql\SQLQuery.py in run_sql(self, sql_text, pagesize)
    475                                                                                                   details['error_message'])
    476         else:
--> 477             return self.get_result(jobId)
    478
    479     def sql_ui_link(self):

c:\users\user_a\appdata\local\programs\python\python35\lib\site-packages\ibmcloudsql\SQLQuery.py in get_result(self, jobId, pagenumber)
    253                     tmpfile = tempfile.NamedTemporaryFile()
    254                     tempfilename = tmpfile.name
--> 255                     cos_client.download_file(Bucket=result_cos_bucket, Key=bucket_object, Filename=tempfilename)
    256
    257                     partition_df = pd.read_parquet(tempfilename)

c:\users\user_a\appdata\local\programs\python\python35\lib\site-packages\ibm_boto3\s3\inject.py in download_file(self, Bucket, Key, Filename, ExtraArgs, Callback, Config)
    170         return transfer.download_file(
    171             bucket=Bucket, key=Key, filename=Filename,
--> 172             extra_args=ExtraArgs, callback=Callback)
    173
    174

c:\users\user_a\appdata\local\programs\python\python35\lib\site-packages\ibm_boto3\s3\transfer.py in download_file(self, bucket, key, filename, extra_args, callback)
    305             bucket, key, filename, extra_args, subscribers)
    306         try:
--> 307             future.result()
    308         # This is for backwards compatibility where when retries are
    309         # exceeded we need to throw the same error from ibm_boto3 instead of

c:\users\user_a\appdata\local\programs\python\python35\lib\site-packages\ibm_s3transfer\futures.py in result(self)
    104             # however if a KeyboardInterrupt is raised we want want to exit
    105             # out of this and propogate the exception.
--> 106             return self._coordinator.result()
    107         except KeyboardInterrupt as e:
    108             self.cancel()

c:\users\user_a\appdata\local\programs\python\python35\lib\site-packages\ibm_s3transfer\futures.py in result(self)
    263         # final result.
    264         if self._exception:
--> 265             raise self._exception
    266         return self._result
    267

c:\users\user_a\appdata\local\programs\python\python35\lib\site-packages\ibm_s3transfer\tasks.py in __call__(self)
    124             # main() method.
    125             if not self._transfer_coordinator.done():
--> 126                 return self._execute_main(kwargs)
    127         except Exception as e:
    128             self._log_and_set_exception(e)

c:\users\user_a\appdata\local\programs\python\python35\lib\site-packages\ibm_s3transfer\tasks.py in _execute_main(self, kwargs)
    148         )
    149
--> 150         return_value = self._main(**kwargs)
    151         # If the task is the final task, then set the TransferFuture's
    152         # value to the return value from main().

c:\users\user_a\appdata\local\programs\python\python35\lib\site-packages\ibm_s3transfer\download.py in _main(self, fileobj, final_filename, osutil)
    601     def _main(self, fileobj, final_filename, osutil):
    602         fileobj.close()
--> 603         osutil.rename_file(fileobj.name, final_filename)
    604
    605

c:\users\user_a\appdata\local\programs\python\python35\lib\site-packages\ibm_s3transfer\utils.py in rename_file(self, current_filename, new_filename)
    269
    270     def rename_file(self, current_filename, new_filename):
--> 271         rename_file(current_filename, new_filename)
    272
    273     def is_special_file(cls, filename):

c:\users\user_a\appdata\local\programs\python\python35\lib\site-packages\ibm_s3transfer\compat.py in rename_file(current_filename, new_filename)
     31                 # that exception.
     32                 raise
---> 33         os.rename(current_filename, new_filename)
     34 else:
     35     rename_file = os.rename

FileExistsError: [WinError 183] Impossibile creare un file, se il file esiste già: 'C:\\Users\\user_a\\AppData\\Local\\Temp\\tmp30c5trxn.D61AFCe5' -> 'C:\\Users\\user_a\\AppData\\Local\\Temp\\tmp30c5trxn'

```

**Comment by barry-hueston** [comment]
Internal Reference:CSAFE-56717

**Comment by lgspST** [comment]
One more thing: the error happens after at least 2 minutes that the run_sql routine is working, not immediately after launching it.

**Comment by vjerch** [comment]
Issue #137 opened on boto/s3transfer: https://github.com/boto/s3transfer/issues/137

**Comment by vjerch** [comment]
@lgspST you are using NamedTemporaryFile.
_c:\users\user_a\appdata\local\programs\python\python35\lib\site-packages\ibmcloudsql\SQLQuery.py in get_result(self, jobId, pagenumber)
ln -->    253                     tmpfile = tempfile.NamedTemporaryFile()_

In your code, on the line above, can you try changing it to _tmpfile = tempfile.NamedTemporaryFile(**delete=False**)_? Python implementation of NamedTemporaryFile uses the O_TEMPORARY flag under Windows, which prevents the file from being accessed if the same flag is not provided which might cause process to hang in your case.

**Comment by lgspST** [comment]
@vjerch I tried what you suggested. Now I get a permission error line 255 of SQLQuery.py

```
Traceback (most recent call last):
  File "C:\Users\Diego\Downloads\petinoapp\main_cli.py", line 32, in <module>
    flagout=menuItems[int(choice)][1]()
  File "C:\Users\Diego\Downloads\petinoapp\dataDL.py", line 55, in vrms_download
    result=query_ts(start,end,'vrms')
  File "C:\Users\Diego\Downloads\petinoapp\dataDL.py", line 38, in query_ts
    res = sqlclient.run_sql(query)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python35\lib\site-packages\ibmcloudsql\SQLQuery.py", line 478, in run_sql
    return self.get_result(jobId)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python35\lib\site-packages\ibmcloudsql\SQLQuery.py", line 255, in get_result
    cos_client.download_file(Bucket=result_cos_bucket, Key=bucket_object, Filename=tempfilename)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_boto3\s3\inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_boto3\s3\transfer.py", line 307, in download_file
    future.result()
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_s3transfer\futures.py", line 106, in result
    return self._coordinator.result()
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_s3transfer\futures.py", line 265, in result
    raise self._exception
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_s3transfer\tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_s3transfer\tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_s3transfer\download.py", line 603, in _main
    osutil.rename_file(fileobj.name, final_filename)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_s3transfer\utils.py", line 271, in rename_file
    rename_file(current_filename, new_filename)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_s3transfer\compat.py", line 25, in rename_file
    os.remove(new_filename)
PermissionError: [WinError 32] Impossibile accedere al file. Il file è utilizzato da un altro processo: 'C:\\Users\\Diego\\AppData\\Local\\Temp\\tmpgyezc3z8'
```

**Comment by vjerch** [comment]
@lgspST can you maybe try explicitly call close on tmpfile in your code?

**Comment by lgspST** [comment]
Sorry, because of the bug, we abandoned the development of this application, and I don't have a windows PC to test what you asked (I used a coworker's pc until now).

**Comment by vjerch** [comment]
@lgspST I was able to reproduce your issue, problem was in ibmcloudsql not handling closing of created NamedTemporaryFile correctly on Windows so the issue should be opened on **https://github.com/IBM-Cloud/sql-query-clients/issues**.

**Comment by vjerch** [comment]
@lgspST ibmcloudsql team addressed and closed the issue: https://github.com/IBM-Cloud/sql-query-clients/issues/46

**Comment by vjerch** [comment]
@lgspST can you pull latest changes from https://github.com/IBM-Cloud/sql-query-clients/tree/master/Python and close this issue if it solves your problem? Thanks!
