### ISSUE TITLE
ImportError: Aspera SDK not installed

### ISSUE THREAD

**Issue by bambrozio** [IBM/ibm-cos-sdk-python-s3transfer#4]
Hi,
I'm afraid there's something wrong with `cos-aspera`. Check this out:

```
$ system_profiler SPSoftwareDataType | grep 'Version:'
      System Version: macOS 10.15.1 (19B88)
      Kernel Version: Darwin 19.0.0

$ python --version
Python 3.6.9 :: Anaconda, Inc.
```

```
$ pip freeze | grep -i 'cos\|boto\|aspera'
boto3==1.7.84
botocore==1.10.84
cos-aspera==0.1.163682
ibm-cos-sdk==2.5.4
ibm-cos-sdk-core==2.5.4
ibm-cos-sdk-s3transfer==2.5.4
```

```
$ python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import ibm_boto3
>>> from ibm_botocore.client import Config, ClientError
>>> from ibm_s3transfer.aspera.manager import AsperaConfig
Traceback (most recent call last):
  File "/Users/bambrozi/miniconda3/envs/iged-airflow-dags/lib/python3.6/site-packages/cos_aspera/faspmanager2.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/Users/bambrozi/miniconda3/envs/iged-airflow-dags/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(/Users/bambrozi/miniconda3/envs/iged-airflow-dags/lib/python3.6/site-packages/cos_aspera/_faspmanager2.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib
  Referenced from: /Users/bambrozi/miniconda3/envs/iged-airflow-dags/lib/python3.6/site-packages/cos_aspera/_faspmanager2.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bambrozi/miniconda3/envs/iged-airflow-dags/lib/python3.6/site-packages/ibm_s3transfer/aspera/futures.py", line 26, in <module>
    from cos_aspera import faspmanager2
  File "/Users/bambrozi/miniconda3/envs/iged-airflow-dags/lib/python3.6/site-packages/cos_aspera/faspmanager2.py", line 17, in <module>
    _faspmanager2 = swig_import_helper()
  File "/Users/bambrozi/miniconda3/envs/iged-airflow-dags/lib/python3.6/site-packages/cos_aspera/faspmanager2.py", line 16, in swig_import_helper
    return importlib.import_module('_faspmanager2')
  File "/Users/bambrozi/miniconda3/envs/iged-airflow-dags/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_faspmanager2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bambrozi/miniconda3/envs/iged-airflow-dags/lib/python3.6/site-packages/ibm_s3transfer/aspera/manager.py", line 36, in <module>
    from ibm_s3transfer.aspera.futures import AsperaTransferCoordinator
  File "/Users/bambrozi/miniconda3/envs/iged-airflow-dags/lib/python3.6/site-packages/ibm_s3transfer/aspera/futures.py", line 29, in <module>
    raise ImportError("Aspera SDK not installed")
ImportError: Aspera SDK not installed
```

**Comment by cpcunningham** [comment]
hi @bambrozio  sorry for the delay in getting back to you
It fails to load the following file
/Library/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib
Can you paste the list of files in this folder
/Library/Frameworks/Python.framework/Versions/3.6/lib/

**Comment by wbhuberIBM** [comment]
@bambrozio - can you paste the list of those files in the folder @cpcunningham specified?  Thanks.
