### ISSUE TITLE
ImportError: Aspera SDK not installed

### ISSUE THREAD

**Issue by kaoru007** [IBM/ibm-cos-sdk-python-s3transfer#6]
Very similar to #4.

```
python --version
Python 3.6.5 :: Anaconda, Inc.
```

```
pip freeze | grep aspera
cos-aspera==0.1.163682
```

```
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/cos_aspera/faspmanager2.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/cos_aspera/_faspmanager2.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib
  Referenced from: /anaconda3/lib/python3.6/site-packages/cos_aspera/_faspmanager2.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/ibm_s3transfer/aspera/futures.py", line 26, in <module>
    from cos_aspera import faspmanager2
  File "/anaconda3/lib/python3.6/site-packages/cos_aspera/faspmanager2.py", line 17, in <module>
    _faspmanager2 = swig_import_helper()
  File "/anaconda3/lib/python3.6/site-packages/cos_aspera/faspmanager2.py", line 16, in swig_import_helper
    return importlib.import_module('_faspmanager2')
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_faspmanager2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server_api.py", line 16, in <module>
    import scheduler
  File "/Users/kaoru/git/translate_at_ibm_services/scheduler.py", line 7, in <module>
    import functions_checks
  File "/Users/kaoru/git/translate_at_ibm_services/functions_checks.py", line 4, in <module>
    import functions_cos
  File "/Users/kaoru/git/translate_at_ibm_services/functions_cos.py", line 3, in <module>
    from ibm_s3transfer.aspera.manager import AsperaTransferManager
  File "/anaconda3/lib/python3.6/site-packages/ibm_s3transfer/aspera/manager.py", line 36, in <module>
    from ibm_s3transfer.aspera.futures import AsperaTransferCoordinator
  File "/anaconda3/lib/python3.6/site-packages/ibm_s3transfer/aspera/futures.py", line 29, in <module>
    raise ImportError("Aspera SDK not installed")
ImportError: Aspera SDK not installed
```

There is no `Python.framework` directory under `/Library/Frameworks`; I've tried to create a symlink to my python install but that did not work.

**Comment by wbhuberIBM** [comment]
@kaoru007 - we do not currently support installing Aspera through python version managers (```pyenv``` or ```anaconda```).  Can you re-attempt installing Aspera using vanilla python 3.6 version from the following website: 

https://www.python.org/downloads/release/python-3610/

**Comment by wbhuberIBM** [comment]
Internally tracking this: CSAFE-71238

**Comment by kaoru007** [comment]
I won't be able to compile vanilla 3.6 into my machine (lots of errors).

So I'll test my code in a Linux VM for now.
Closing, thanks.
